homeassistant:
  enabled: false
frontend:
  enabled: true
  port: 8081
  host: 0.0.0.0
mqtt:
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyACM0
  adapter: ezsp
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
version: 4
devices:
  '0xa4c13825a5855f1b':
    friendly_name: '0xa4c13825a5855f1b'
